Object#namespace was removed from MoreCoreExtensions by #20
https://github.com/ManageIQ/more_core_extensions/pull/20
fixes https://github.com/ManageIQ/manageiq/issues/6859

Error details:
     Ovirt::Base #update
     Failure/Error: vm.update { |x| x.description("test description") }
     NameError:
       undefined local variable or method `namespace' for #<Ovirt::Vm:0x00561be1ab8170>
     # ./lib/ovirt/base.rb:269:in `method_missing'
     # ./lib/ovirt/base.rb:322:in `block in update'
     # /home/bdunne/.gem/ruby/2.2.4/gems/nokogiri-1.6.6.4/lib/nokogiri/xml/builder.rb:293:in `initialize'
     # ./lib/ovirt/base.rb:321:in `new'
     # ./lib/ovirt/base.rb:321:in `update'
     # ./spec/base_spec.rb:23:in `block (2 levels) in <top (required)>'